# Generated by Django 5.0.4 on 2024-04-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
