# Generated by Django 5.0.4 on 2024-04-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_event_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
