# Generated by Django 5.0.4 on 2024-04-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0005_alter_ticket_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='key',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
